# Generated by Django 5.1.4 on 2025-01-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='image',
            new_name='logo',
        ),
    ]
